SELECT RecordType, CUSTOMER, ORDER_NO, OO_LIN, OO_PO, PART, [DESCRIPTION], QTY_SHIPPED, QTY_ORDERED, QTY_BO, PRICE, GL_ACCOUNT, VectorData FROM [dbo].[V_RAG_Vector] WHERE RecordType = 'OpenOrder' AND CUSTOMER = 'TRELL2' ORDER BY ORDER_NO ASC

-- SELECT * FROM [dbo].[V_RAG_Vector] WHERE RecordType = 'OpenOrder' AND ORDER_NO = 91645

