SELECT RecordType, CUSTOMER, ORDER_NO, OO_LIN, OO_PO, PART, [DESCRIPTION], QTY_SHIPPED, QTY_ORDERED, QTY_BO, PRICE, GL_ACCOUNT FROM [dbo].[V_RAG_Vector] WHERE RecordType = 'OpenOrder' AND CUSTOMER = 'ATKLAU' ORDER BY ORDER_NO ASC

-- SELECT COUNT(*) FROM [dbo].[V_RAG_Vector] WHERE RecordType = 'OpenOrder'
